import React from 'react';
import { StatusBar } from 'expo-status-bar';
import { AuthProvider } from './src/context/AuthContext';
import { ErrorProvider } from './src/context/ErrorContext';
import { PaperProvider } from 'react-native-paper';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { ErrorBoundary } from './src/components/ErrorBoundary';
import { AppNavigator } from './src/navigation/AppNavigator';
import { LocalizationProvider } from './src/localization/LocalizationProvider';
import { ThemeProvider, useThemeMode } from './src/context/ThemeContext';
import { FeatureFlagsProvider } from './src/context/FeatureFlagsContext';

// Storybook toggle - Import build-time constant
// This file is generated by scripts/generate-storybook-flag.js
import { IS_STORYBOOK_MODE } from './storybook-config';
const SHOW_STORYBOOK = IS_STORYBOOK_MODE;

// Debug log (only in development)
if (__DEV__) {
  console.log('🔍 Storybook Mode:', SHOW_STORYBOOK ? 'ENABLED' : 'DISABLED');
}

// Paper Theme Wrapper
const PaperThemeWrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { theme } = useThemeMode();
  return <PaperProvider theme={theme}>{children}</PaperProvider>;
};

const App: React.FC = () => {
  // Load Storybook if enabled - use dynamic import to isolate
  if (SHOW_STORYBOOK) {
    // Use Component Showcase as fallback since Storybook has compatibility issues
    const ComponentShowcase = require('./src/screens/ComponentShowcase').ComponentShowcase;
    return (
      <ErrorBoundary>
        <SafeAreaProvider>
          <FeatureFlagsProvider>
            <ThemeProvider>
              <PaperThemeWrapper>
                <ComponentShowcase />
              </PaperThemeWrapper>
            </ThemeProvider>
          </FeatureFlagsProvider>
        </SafeAreaProvider>
      </ErrorBoundary>
    );
  }

  // Normal app
  return (
    <ErrorBoundary>
      <SafeAreaProvider>
        <FeatureFlagsProvider>
          <ThemeProvider>
            <PaperThemeWrapper>
              <LocalizationProvider>
                <AuthProvider>
                  <ErrorProvider>
                    <AppNavigator />
                    <StatusBar style="auto" />
                  </ErrorProvider>
                </AuthProvider>
              </LocalizationProvider>
            </PaperThemeWrapper>
          </ThemeProvider>
        </FeatureFlagsProvider>
      </SafeAreaProvider>
    </ErrorBoundary>
  );
};

export default App;
