// Entry point for React Native Storybook v10.
// The `.rnstorybook/storybook.requires` file (generated by `npm run storybook-generate`)
// bootstraps Storybook and exports a `view` instance.
// We must call `view.getStorybookUI()` to obtain the actual React component.
import AsyncStorage from '@react-native-async-storage/async-storage';
// eslint-disable-next-line import/no-unresolved
import { view } from '../.rnstorybook/storybook.requires';

const StorybookUIRoot = view.getStorybookUI({
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
});

export default StorybookUIRoot;
